spring:
  application:
    name: spring-cloud-eureka
  profiles:
    active: registry1

---
spring:
  profiles: registry1
server:
  port: 8000
eureka:
  instance:
    hostname: registry1
  client:
    serviceUrl:
      defaultZone: http://registry2:8001/eureka/,http://registry3:8002/eureka/

---
spring:
  profiles: registry2
server:
  port: 8001
eureka:
  instance:
    hostname: registry2
  client:
    serviceUrl:
      defaultZone: http://registry1:8000/eureka/,http://registry3:8002/eureka/

---
spring:
  profiles: registry3
server:
  port: 8002
eureka:
  instance:
    hostname: registry3
  client:
    serviceUrl:
      defaultZone: http://registry1:8000/eureka/,http://registry2:8001/eureka/

