spring:
  application:
    name: netflix-zuul
server:
  port: 9400
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9300/eureka/
zuul:
  routes:
    consumer-hello:
      path: /consumer-hello/**
      service-id: netflix-eureka-consumer-hello
ribbon:
  ReadTimeout: 2000  #请求处理的超时时间
  ConnectTimeout: 3000  #请求连接的超时时间