spring:
  application:
    name: nacos-consumer-hello
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 9001
# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true
