spring:
  application:
    name: netflix-eureka-consumer-hello
server:
  port: 9302
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9300/eureka/
feign:
  hystrix:
    enabled: true
